### ISSUE TITLE
不能拖拽

### ISSUE THREAD

**Issue by lh1241698502** [mikaelzero/mojito#105]
在最新的demo中跑了一遍代码，发现在 查看原图 和 Activity自定义覆盖层 这2个场景下，不能拖拽，点击查看原图直接关闭了预览

**Comment by sceneren** [comment]
找了下原因，好像是在ImageMojitoFragment里面的startAnim()触发了replaceImageUrl() 然后触发了loadImageFail()
<img width="944" alt="WX20220421-161104@2x" src="https://user-images.githubusercontent.com/6612998/164410231-8a61e743-bee1-44d8-9fa9-44a590b5aaed.png">
所以的点击事件都被loadingLayout的点击事件拦截了
<img width="838" alt="image" src="https://user-images.githubusercontent.com/6612998/164410507-6645b9bd-dee9-4bc3-b11f-42721c6fb434.png">
