### ISSUE TITLE
FragmentCoverLoader中获取当前是第几个position怎么获取呢 需要判断当前是第几个position处理添加布局的逻辑

### ISSUE THREAD

**Issue by silveryTitan** [mikaelzero/mojito#116]
FragmentCoverLoader中获取当前是第几个position怎么获取呢 需要判断当前是第几个position处理添加布局的逻辑

**Comment by silveryTitan** [comment]
我看了下 引入module后 直接在ImageMojitoFragment的fragmentCoverLoader?.attach把fragmentConfig.position加上后 接口也对应加上就可以 对吗？

**Comment by mikaelzero** [comment]
是的
