### ISSUE TITLE
大图显示效果根据传进去的views(imageviews)决定

### ISSUE THREAD

**Issue by BestCoderXQX** [MikaelZero/mojito#24]
当imageview的宽度为wrap_content的时候  大图显示正确 长宽按原图比例显示  但是会导致原图因为wrap 造成宽度显示不全（比如宽度高度都为100dp ，显示的是一个长方形图片,宽度会显示不全）

当imageview的宽度为match的时候  ，小图显示正确 ，但是大图显示会局限在一个正方形区域里，导致原图是长方形的话 ，大图图片高度显示不全

目前需求 小图为正方形区域显示 ， 大图原图比例显示 ，上面两个宽度的设置都会有一方不满足

**Comment by MikaelZero** [comment]
提供下你所测试的图片地址
