### ISSUE TITLE
第一次加载完后已经缓存了,第二次打开为啥还是会显示进度条

### ISSUE THREAD

**Issue by dary123** [MikaelZero/mojito#27]
第一次加载完后已经缓存了,第二次打开为啥还是会显示进度条

**Comment by MikaelZero** [comment]
这个已经在做修改  还没更新版本

**Comment by dary123** [comment]
好的，谢谢，公司要求的，其实我个人觉得没多大影响

**Comment by dary123** [comment]
> 这个已经在做修改 还没更新版本
什么时候更新版本呀，好急呀，麻烦大神了

**Comment by MikaelZero** [comment]
最近公司很忙 实在没什么时间  之前改了一点  到时候我push到develop的分支上

**Comment by dary123** [comment]
> 最近公司很忙 实在没什么时间 之前改了一点 到时候我push到develop的分支上

恩恩，谢谢，上传好了告诉我一下

**Comment by MikaelZero** [comment]
昨天已经上传了  你可以看一看

**Comment by dary123** [comment]
> 昨天已经上传了 你可以看一看

我使用的grandle构建引用的你的库，请问怎么引用develope分支呢

**Comment by MikaelZero** [comment]
dev分支没有库  只能你下载到本地自己依赖

**Comment by dary123** [comment]
> dev分支没有库 只能你下载到本地自己依赖

怎么下载啊，git还不太会用，是不是下载了分支还要和之前的合并

**Comment by MikaelZero** [comment]
不用 dev分支 是单独的代码

**Comment by dary123** [comment]
额，大神，能直接告诉我在哪里可以下载整个修改完后模块库吗，我以模块的形式导入

**Comment by MikaelZero** [comment]
切换到dev分支 直接下载就行了

**Comment by dary123** [comment]
> 切换到dev分支 直接下载就行了

哥，你是不是直接把loading隐藏了呀，我第一次打开也没用loading了现在

**Comment by dary123** [comment]
> 切换到dev分支 直接下载就行了

第一次打开会闪一下，这个如果能优化下就好了

**Comment by MikaelZero** [comment]
你可以看下代码 简单修改下 这部分的逻辑不难的

**Comment by dary123** [comment]
> 你可以看下代码 简单修改下 这部分的逻辑不难的

长按图片的监听是不是没有，想要做保存操作

**Comment by dary123** [comment]
> 你可以看下代码 简单修改下 这部分的逻辑不难的

找到了，有长按的

**Comment by dary123** [comment]
tgia.setOnItemClickListener(new OnItemClickListener() {
                        @Override
                        public void onItemClick(BaseQuickAdapter adapter, View view, int position) {
                            new Diooto(mContext)
                                    .urls(originPic)
                                    .type(DiootoConfig.PHOTO)
                                    .immersive(true)
                                    .fullscreen(true)
                                    .position(position, 0)
                                    .views(find_conpic, R.id.item_grida_image)
                                    .loadPhotoBeforeShowBigImage((sketchImageView, position12) -> {
                                        sketchImageView.displayImage(thumbPicAdd[position12]);
                                        sketchImageView.setOnLongClickListener(new View.OnLongClickListener() {
                                            @Override
                                            public boolean onLongClick(View v) {
                                                SheetDialog ssd = new SheetDialog(mContext, "取消").builder();
                                                ssd.setTitle("");
                                                ssd.addSheetItem("保存", SheetDialog.SheetItemColor.Black, new SheetDialog.OnSheetItemClickListener() {

                                                    @Override
                                                    public void onClick(int which) {
                                                        Log.e("33","点击保存");
                                                        try {
                                                            URL urlAdd = null;
                                                            urlAdd = new URL(item.getPostAttach().get(0).getAttachPath());
                                                            HttpURLConnection connAdd = (HttpURLConnection) urlAdd.openConnection();
                                                            connAdd.setConnectTimeout(6*1000);  // 注意要设置超时，设置时间不要超过10秒，避免被android系统回收
                                                            if (connAdd.getResponseCode() != 200) throw new RuntimeException("请求url失败");
                                                            InputStream inSreamAdd = connAdd.getInputStream();
                                                            //把图片保存到项目的根目录
                                                            String randNumAdd = CommonUtils.getRandomId();
                                                            CommonUtils.readAsFile(inSreamAdd, new File(Environment.getExternalStorageDirectory()+"/"+"downpic"+randNumAdd+".jpg"));
                                                            File myFile = new File(Environment.getExternalStorageDirectory()+"/"+"downpic"+randNumAdd+".jpg");
                                                            Intent intent = new Intent(Intent.ACTION_MEDIA_SCANNER_SCAN_FILE);
                                                            Uri uri = Uri.fromFile(myFile);
                                                            intent.setData(uri);
                                                            mContext.sendBroadcast(intent);
                                                            CommonUtils.comToast(mContext,"已保存至相册");
                                                        } catch (MalformedURLException e) {
                                                            Log.e("33","异常1:"+e.toString());
                                                        } catch (IOException e) {
                                                            Log.e("33","异常2:"+e.toString());
                                                        } catch (Exception e) {
                                                            Log.e("33","异常3:"+e.toString());
                                                        }
                                                    }
                                                }).show();
                                                return false;
                                            }
                                        });
在长按事件里添加一个底部弹出dialog，dialog里的item点击事件没有响应

**Comment by MikaelZero** [comment]
这个和框架应该没关系吧

**Comment by dary123** [comment]
> 这个和框架应该没关系吧

你那边可以吗，有没有试过长按保存功能

**Comment by MikaelZero** [comment]
只要长按的事件能够响应 保存和框架是无关的  你检查下代码
