### ISSUE TITLE
显示表情包小图的问题

### ISSUE THREAD

**Issue by feimenggo** [MikaelZero/mojito#36]
表情包的小图尺寸较小，放大后就非常模糊，如下：

![模糊](https://user-images.githubusercontent.com/12608693/86314998-9d942900-bc5b-11ea-9d2c-96cc022fc24c.png)

正常应该这样显示：

![正常](https://user-images.githubusercontent.com/12608693/86315004-9ff68300-bc5b-11ea-8129-c81c69fc7d6e.png)

如果直接在代码里将ScaleType.FIT_CENTER改成ScaleType.CENTER_INSIDE的话，动画执行完毕会突然从大图变成小图，体验不好，我应该怎么做呢？

`

    override fun loadAnimFinish() {
        if (isLongHeightImage || isLongWidthImage) {
        } else {
            sketchImageView.scaleType = ImageView.ScaleType.CENTER_INSIDE
        }
    }

`

这是表情图片地址：[图片](https://pome.obs.cn-east-3.myhuaweicloud.com/dynamicImage/tiny-857-2020-06-23-20-44-23.jpg?w=100&h=100)

**Comment by MikaelZero** [comment]
提供一下原图地址
因为之前发现大部分的这种小图 在不同app上显示的效果都是宽度充满的  所以没有处理这种非常小的图

如果一定要适配  需要修改自定义view里的逻辑了  较为麻烦

**Comment by MikaelZero** [comment]
如果一定要这种效果
我可以放到新需求里，但是优先级会比较低

**Comment by feimenggo** [comment]
好滴，我们的APP里用户经常发表情包，都说图片太模糊了，最后就有这样的需求了。

**Comment by MikaelZero** [comment]
经过考虑，暂时不支持这种小图
