### ISSUE TITLE
如何设置加载中的占位图？

### ISSUE THREAD

**Issue by feimenggo** [MikaelZero/mojito#37]
当网速慢的时候，点击图片没有任何转场效果，图片加载完会立刻显示。
录屏：
[录屏.zip](https://github.com/MikaelZero/mojito/files/4876388/default.zip)

**Comment by MikaelZero** [comment]
这个没有做处理 后续会改成直接通过透明度的方式显示加载图片的效果
无法做占位图，因为无法获取到图片的宽高

**Comment by feimenggo** [comment]
哦哦，如果图片地址上附带了宽高信息呢？像这样：https://pome.obs.cn-east-3.myhuaweicloud.com/dynamicImage/pome-782-2020-07-03-16-19-53.jpg?w=1019&h=16380

**Comment by feimenggo** [comment]
另外，显示长图的时候无法滚到图片底部，只能靠惯性滚动到底部。
[device-2020-07-06-101838.zip](https://github.com/MikaelZero/mojito/files/4876456/device-2020-07-06-101838.zip)

**Comment by MikaelZero** [comment]
好的 有时间把宽高配置加上 长图那个少了个逻辑 应该加上up事件的判断

**Comment by feimenggo** [comment]
嗯嗯，辛苦了。

**Comment by MikaelZero** [comment]
我测试了下长图没有问题 
是不是你设置了原图和缩略图 两个图的大小时不一样的？

**Comment by feimenggo** [comment]
嗯，确实原图和缩略图大小不一样，比例一样。不过，只设置原图没有缩略图时也会有这种问题。

**Comment by feimenggo** [comment]
![图片](https://user-images.githubusercontent.com/12608693/86553896-9aac7780-bf7e-11ea-888e-fe2cf64ef054.png)

[device-2020-07-06-114659.zip](https://github.com/MikaelZero/mojito/files/4876680/device-2020-07-06-114659.zip)

**Comment by MikaelZero** [comment]
具体的代码发一下  因为我没发现这个问题

**Comment by feimenggo** [comment]
master分支
[长图无法滚到底部.zip](https://github.com/MikaelZero/mojito/files/4881949/default.zip)

**Comment by feimenggo** [comment]
单张图的时候，需要快速多次滚动才会出现

**Comment by MikaelZero** [comment]
1.5版本已添加加载过程的进度条
长图问题已解决
