### ISSUE TITLE
大图长按后，怎么在当前大图查看页面显示一个dialog啊

### ISSUE THREAD

**Issue by aiynmm** [MikaelZero/mojito#38]
如题：目前显示的对话框在图片列表的activity中，也就是说这个dialog怎么拿到查看的大图那个activity啊？求解！

**Comment by MikaelZero** [comment]
onLongClick中的第一个参数 fragmentActivity 就是大图所在的Activity

**Comment by aiynmm** [comment]
> onLongClick中的第一个参数 fragmentActivity 就是大图所在的Activity

👌
