### ISSUE TITLE
换了一个视频控件，缩放后，控件只占屏幕的一半了

### ISSUE THREAD

**Issue by zhangkun0018** [MikaelZero/mojito#42]
再使用的时候换了一个JzvdStd视频播放控件，结果缩放结束后，控件宽度只占屏幕的一半
![微信图片_20200814170235](https://user-images.githubusercontent.com/23331766/90233371-a1b58800-de50-11ea-93b3-8ead3843b1bc.jpg)

**Comment by MikaelZero** [comment]
这个和 JzvdStd 有关系了，可以参考demo中的逻辑
你需要自己把显示模式更改
