### ISSUE TITLE
依赖问题

### ISSUE THREAD

**Issue by lixiongh-hou** [MikaelZero/mojito#43]
大佬，我依赖这个implementation 'net.mikaelzero.mojito:GlideImageLoader:1.1.0'
依赖报错
Failed to resolve: net.mikaelzero.mojito:GlideImageLoader:1.1.0
Show in Project Structure dialog
Affected Modules: app
项目是java代码，不是Kotlin

**Comment by MikaelZero** [comment]
加了这个了吗  
`repositories {
        maven { url 'https://dl.bintray.com/mikaelzero/maven'}
    }`
项目加上kotlin试试

**Comment by lixiongh-hou** [comment]
嗯嗯，可以了
