### ISSUE TITLE
设置DefaultPercentProgress后，没有加载过程，显示透明页面

### ISSUE THREAD

**Issue by onecoders** [MikaelZero/mojito#44]
.setProgressLoader(object : InstanceLoader<IProgress> {
                    override fun providerInstance(): IProgress {
                        return DefaultPercentProgress()
                    }
                })
设置后，加载页面直接显示透明，加载完成才有图片显示
PS: 之前的Diooto是有加载进度显示的，背景是黑色的

**Comment by onecoders** [comment]
![image](https://user-images.githubusercontent.com/3477738/91786952-603c1f80-ec3b-11ea-9944-5250f2a4a6fb.png)

**Comment by onecoders** [comment]
现在点击一张大图片，要先加载完成才能显示，如果图片没有加载完成，页面就卡死状态；多张切换的时候，没有加载完成的图片，页面会显示透明

**Comment by onecoders** [comment]
能否像以前一样，先出来页面，背景黑色，然后显示加载进度？

**Comment by MikaelZero** [comment]
OK  后续考虑加上

**Comment by MikaelZero** [comment]
1.5版本已添加
