### ISSUE TITLE
长图滑动监听

### ISSUE THREAD

**Issue by lixiongh-hou** [MikaelZero/mojito#46]
作者您好，有没有长图在滑动时候的监听，就是类似Bilibili滑动长图的时候会隐藏一些文字之类的信息

**Comment by MikaelZero** [comment]
SimpleMojitoViewCallback  有一个onDrag 函数  ，返回了滑动过程中的移动距离

**Comment by lixiongh-hou** [comment]
`.setOnMojitoListener(object : SimpleMojitoViewCallback(){
                        override fun onDrag(view: MojitoView, moveX: Float, moveY: Float) {
                            Log.e("测试", "moveY$moveY,moveX$moveX")
                        }
                    })`
是这样吗，这貌似是拖拽才会回调的

**Comment by MikaelZero** [comment]
这个确实没有开放出来  
可以在SketchContentLoaderImpl的基础上修改  然后初始化的时候直接设置自己的实现类

**Comment by MikaelZero** [comment]
1.5版本已更新
可调用 SimpleMojitoViewCallback 的 onLongImageMove  
返回的是长图的滑动比例

**Comment by lixiongh-hou** [comment]
好的
