### ISSUE TITLE
build.gradle由原来的1.1.0升级到1.5后，显示图片的代码没有改，直接报错

### ISSUE THREAD

**Issue by onecoders** [MikaelZero/mojito#49]
![image](https://user-images.githubusercontent.com/3477738/93415266-b1077580-f8d5-11ea-8f8f-9b3f1a1cfe99.png)

**Comment by MikaelZero** [comment]
本地有办法复现吗

**Comment by MikaelZero** [comment]
另外我看到bootstrap相关的东西  是有和RN之类的一起使用吗

**Comment by onecoders** [comment]
> 另外我看到bootstrap相关的东西 是有和RN之类的一起使用吗

没有和RN一起使用

**Comment by onecoders** [comment]
Invoke-customs are only supported starting with Android O (--min-api 26)

**Comment by onecoders** [comment]
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
加了这个就好了
