### ISSUE TITLE
不使用RecycleView的时候使用指示器无效

### ISSUE THREAD

**Issue by Idumuzhou** [MikaelZero/mojito#50]
noViewBtn.setOnClickListener {
            Mojito.with(context)
                .urls(SourceUtil.getSingleImage())
                .setIndicator(NumIndicator())  //不使用RecycleView的时候使用指示器无效
                .start()
        }
        noViewViewPagerBtn.setOnClickListener {
            Mojito.with(context)
                .urls(SourceUtil.getNormalImages())
                .setIndicator(NumIndicator())
                .start()
        }

**Comment by MikaelZero** [comment]
fix in version 1.5.2
