### ISSUE TITLE
glide 等相关库的引用能否换成compileOnly，防止引入冲突？

### ISSUE THREAD

**Issue by guo-hang** [MikaelZero/mojito#51]

**Comment by MikaelZero** [comment]
是不同版本的glide的冲突问题吗

**Comment by guo-hang** [comment]
是的，还有okhttp相关库的版本冲突

**Comment by MikaelZero** [comment]
能提供下你项目的okhttp版本还有glide版本吗

**Comment by guo-hang** [comment]
我这边okhhtp 版本只有3.12.1， 引入后会使网络相关的地方要修改，我这边直接将GlideImageLoader中的类copy进项目里了。compileOnly应该并不能解决我的问题，只是感觉这样使用可能会更好点。

**Comment by MikaelZero** [comment]
也可以 毕竟GlideImageLoader的代码也不多  可以自己实现
