### ISSUE TITLE
长按无效的问题

### ISSUE THREAD

**Issue by qienanxiang** [MikaelZero/mojito#53]
代码如下：
```
imImage.setOnClickListener(v->{
            Mojito.with(this)
                    .urls(path)
                    .views(imImage)
                    .setOnMojitoListener(new SimpleMojitoViewCallback() {
                        @Override
                        public void onLongClick(@Nullable FragmentActivity fragmentActivity, @NotNull View view, float x, float y, int position) {
                            Toast.makeText(fragmentActivity,"onLongClick",Toast.LENGTH_LONG).show();
                        }
                    })
                    .start();
        });

```
偶尔会出现toast，概率极低，不知道什么原因？

**Comment by MikaelZero** [comment]
是长按的情况下，偶尔出现toast吗

**Comment by qienanxiang** [comment]
> 是长按的情况下，偶尔出现toast吗

是的，换成dialog，然后用的是FragmentActivity  出现在图片下面，也是偶尔出现，长按似乎不灵敏，但是安装实例的apk，长按toast每次都会出现的

**Comment by MikaelZero** [comment]
1. 打包成apk  长按不会失效
2. 自己通过项目运行出来的，长按偶尔会失效

是这样吗

**Comment by boyad-zl** [comment]
我这边也经常出现这个问题，看日志上显示，长按很容易就触发变成滑动事件了，希望作者能够将长按的阈值进行公开调整

**Comment by qienanxiang** [comment]
> 1. 打包成apk  长按不会失效
> 2. 自己通过项目运行出来的，长按偶尔会失效
> 
> 是这样吗

不是的，是你的示例二维码下载的apk，长按可以，但是自己项目中的运行还是打包都不可以，然后自己新建一个demo，只有mojito，长按还是概率很低.

**Comment by MikaelZero** [comment]
我在demo里试了一下
```java
singleIv.setOnClickListener {
            Mojito.with(context)
                .urls(SourceUtil.getSingleImage())
                .views(singleIv)
                .setOnMojitoListener(object : SimpleMojitoViewCallback() {
                    override fun onLongClick(fragmentActivity: FragmentActivity?, view: View, x: Float, y: Float, position: Int) {
                        Toast.makeText(fragmentActivity, "long click", Toast.LENGTH_SHORT).show()
                    }
                })
                .start()
        }
```

长按都是可以响应的，有试过demo吗

**Comment by qienanxiang** [comment]
> 我在demo里试了一下
> 
> ```java
> singleIv.setOnClickListener {
>             Mojito.with(context)
>                 .urls(SourceUtil.getSingleImage())
>                 .views(singleIv)
>                 .setOnMojitoListener(object : SimpleMojitoViewCallback() {
>                     override fun onLongClick(fragmentActivity: FragmentActivity?, view: View, x: Float, y: Float, position: Int) {
>                         Toast.makeText(fragmentActivity, "long click", Toast.LENGTH_SHORT).show()
>                     }
>                 })
>                 .start()
>         }
> ```
> 
> 长按都是可以响应的，有试过demo吗

今天下载demo试了一下，长按概率依然很低，然后试着调试一下，发现当ACTION_MOVE 且mTranslateX = mYDistanceTraveled = 0时，依然判定为drag，就修改了一下判定条件：

`
//改动：(Math.abs(mTranslateX) > Math.abs(mYDistanceTraveled) 修改为 >=
// if touch slop too short,un need event
                if (Math.abs(mYDistanceTraveled) < touchSlop && (Math.abs(mTranslateX) >= Math.abs(mYDistanceTraveled) && !isDrag)) {
                    mYDistanceTraveled = 0;
                    if (isTouchPointInContentLayout(contentLayout, event)) {
                        break;
                    }
                    break;
                }
`

之后长按基本都可以的
