### ISSUE TITLE
空指针报错：Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by boyad-zl** [MikaelZero/mojito#54]
在bugly的上传日志中发现，偶尔会出现空指针报错：定位到出错位置为：ImageMojitoFragment -> onViewCreated -> 
`mImageLoader?.loadImage(showView.hashCode(), uri, !isFile, object : DefaultImageCallback() {
            override fun onSuccess(image: File) {
                mainHandler.post {
                    mViewLoadFactory?.loadSillContent(showView!!, Uri.fromFile(image))
                    startAnim(image)
                }
            }

            override fun onFail(error: Exception) {
                mainHandler.post {
                    startAnim(ScreenUtils.getScreenWidth(context), ScreenUtils.getScreenHeight(context), fragmentConfig.originUrl)
                }
            }
        })`

失败以后应该是会存在空指针报错的， 希望作者早日修复！

**Comment by boyad-zl** [comment]
另外，bugly日志显示，还在ImageMojitoFragment 还存在空指针报错： loadingLayout must not be null

**Comment by MikaelZero** [comment]
提供下引用的版本号

**Comment by MikaelZero** [comment]
另外最好能具体贴下bugly的截图
现在是不是两个地方出现了空指针？

**Comment by boyad-zl** [comment]
![image](https://user-images.githubusercontent.com/19161499/103531954-4babb480-4ec5-11eb-8933-6942785ebd69.png)
![image](https://user-images.githubusercontent.com/19161499/103532023-78f86280-4ec5-11eb-8052-da502cde987c.png)

**Comment by boyad-zl** [comment]
mojitoVersion = '1.5.5'

**Comment by MikaelZero** [comment]
这两个空指针是由于handle的post后没有做判断导致的，发个小版本修复
这个问题等另一个长按问题一起发布
