### ISSUE TITLE
可以提供拖拽关闭的阈值配置吗

### ISSUE THREAD

**Issue by KunMinX** [MikaelZero/mojito#55]
想和微信一样的，轻轻往下一拽就允许关闭。最好是允许在 config 中配置阈值距离。

我已找到可以在 MojitoView 调试和修改的地方，奈何这个项目 clone 到本地跑不起来，无法自行修改和测试（gradle build 20 分钟也没跑起来，可能是网络问题，普通项目 20s 跑起）

**Comment by MikaelZero** [comment]
还有其他需要可配置的吗
可以发个小版本加上

**Comment by KunMinX** [comment]
@MikaelZero 

暂时没有了，这个库封装的很棒，功能考虑的很全面，感谢作者的输出！

**Comment by MikaelZero** [comment]
这个值是有的  IMojitoConfig 里的maxTransYRatio  默认是 0.16 也就是屏幕高度*0.16

**Comment by MikaelZero** [comment]
在Mojito的initialize的第三个参数 就是IMojitoConfig  
你可以自己写一个实现类

**Comment by KunMinX** [comment]
@MikaelZero 
原来如此，谢谢啦
