### ISSUE TITLE
Android 5.0运行会carsh

### ISSUE THREAD

**Issue by chenjx888** [MikaelZero/mojito#56]
主要错误：requestFeature() must be called before adding content
机型：魅族 m2

**Comment by MikaelZero** [comment]
源码里这行  https://github.com/MikaelZero/mojito/blob/b648083449b6782b1fb34177b4db1732b8fa11ce/mojito/src/main/java/net/mikaelzero/mojito/ui/ImageMojitoActivity.kt#L35

和34行的互换，会出现同样的错误吗

**Comment by MikaelZero** [comment]
supportRequestWindowFeature(Window.FEATURE_NO_TITLE)  
这句代码只加在onCreate前面，其他不动会有问题吗

**Comment by chenjx888** [comment]
按照你的方法改就好了
