### ISSUE TITLE
加载图片的卡顿、掉帧等问题

### ISSUE THREAD

**Issue by KunMinX** [MikaelZero/mojito#58]
1.通过用户上传的大量图片样本的测试后发现，有些图片在点击查看大图时，转场过程中会十分卡顿（掉帧），如：

https://i.loli.net/2021/02/05/b1eCjrIW5yqow2s.jpg

https://i.loli.net/2021/02/05/bsh78Ov9aHVTJPc.jpg

（通过 demo 的“查看本地图片” 加载上述图片也是一样的卡顿）

2.此外，想调试，但无奈不熟悉 gradle 且没能将项目跑起来，望解决 gradle 依赖问题。（以下是项目 clone 后一行代码没改，直接跑的结果：）

Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve androidx.fragment:fragment:{strictly 1.0.0}.
     Required by:
         project :app
      > Cannot find a version of 'androidx.fragment:fragment' that satisfies the version constraints: 
           Dependency path 'mojito:app:unspecified' --> 'androidx.appcompat:appcompat:1.2.0' --> 'androidx.fragment:fragment:1.1.0'
           Constraint path 'mojito:app:unspecified' --> 'androidx.fragment:fragment:{strictly 1.0.0}' because of the following reason: debugRuntimeClasspath uses version 1.0.0
           Dependency path 'mojito:app:unspecified' --> 'com.google.android.material:material:1.2.1' --> 'androidx.fragment:fragment:1.0.0'
           Dependency path 'mojito:app:unspecified' --> 'com.github.bumptech.glide:glide:4.11.0' --> 'androidx.fragment:fragment:1.0.0'
           Dependency path 'mojito:app:unspecified' --> 'com.google.android.material:material:1.2.1' --> 'androidx.viewpager2:viewpager2:1.0.0' --> 'androidx.fragment:fragment:1.1.0'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by KunMinX** [comment]
https://i.loli.net/2021/02/05/fiEUhAPJSOYld97.jpg

以及这张图，在 1080p 的手机下无法拖拽关闭

**Comment by MikaelZero** [comment]
卡顿问题已解决
gradle的问题尝试升级AS到最新版

**Comment by MikaelZero** [comment]
https://i.loli.net/2021/02/05/fiEUhAPJSOYld97.jpg 
这张图，在非1080P的手机下显示可以drag吗？
在其他分辨率下还有其他长图会出现无法drag吗？

**Comment by MikaelZero** [comment]
已找到原因

**Comment by KunMinX** [comment]
@MikaelZero 

经测试，上述该图在 2k 屏的手机上也是无法 drag。

而且并非所有长图都无法 drag，上述提供的样本是无法 drag 的长图之一。

以下这张图在 “传统 1080p”（非全面屏）手机上无法 drag 关闭

https://i.loli.net/2021/02/07/4y5CXcvPh9UHOK1.jpg

**Comment by KunMinX** [comment]
@MikaelZero 

好的

**Comment by KunMinX** [comment]
经测试已无卡顿现象，且图片均可 drag 关闭了

**Comment by KunMinX** [comment]
经排查，是网络原因，
有这方面问题的开发者，可通过将 项目根目录下的 build.gradle 中的 buildscript repositories 和 allprojects repositories 下的 maven { url 'https://maven.google.com' }  给注释掉即可。

好了，我要去阅读作者的源码和干货了
