### ISSUE TITLE
图片无法通过手势关闭

### ISSUE THREAD

**Issue by KunMinX** [MikaelZero/mojito#59]
在 pixel 测试机的 原生 Android 10、11 下 有屏幕侧边左滑 “返回” 的手势功能，（不是图片本身的 drag，是屏幕边缘的左滑）
测试本项目的 apk 支持手势返回，
但本项目的依赖添加到私人 demo 中，均无法手势返回。

**Comment by KunMinX** [comment]
在私人 demo 中调试发现，手势左滑时，触发了 MojitoView 的 actionCancel

case MotionEvent.ACTION_CANCEL:
                backToNormal();
                break;

并且由于 backToNormal()，导致 isAnimating = true，继而导致后续 keyDown ==back 驱动的 backToMin() 因 isAnimating 而被提前 return

**Comment by MikaelZero** [comment]
pixel 测试机是真机吗？

**Comment by KunMinX** [comment]
@MikaelZero 

是的，是 pixel3 真机。
在 demo 中没问题，在引入 dependency 的个人 demo 中会出现问题

**Comment by MikaelZero** [comment]
按逻辑来说，触发了ACTION_CANCEL时候代表着他应该需要回到normal状态，我修改下backToNormal为顺发，后面发个版本，把那几个都问题都会提交

**Comment by KunMinX** [comment]
@MikaelZero 

好嘞，谢谢你

**Comment by KunMinX** [comment]
经测试，pixel3 已可手势关闭了
