### ISSUE TITLE
最新的版本，视频和图片混合轮播的问题

### ISSUE THREAD

**Issue by onecoders** [MikaelZero/mojito#60]
视频和图片混合，先点击图片，放大展示后，在图片切换到视频后，视频不会播放，只会展示视频的封面图

**Comment by onecoders** [comment]
![image](https://user-images.githubusercontent.com/3477738/107113201-6a241780-6898-11eb-8740-a144b1a44aac.png)
这个版本倒是可以的，先点击图片，放大展示后，再滑动到视频，可以播放视频

**Comment by MikaelZero** [comment]
我试了下demo是可以的，项目里的视频链接失效了，你可以试试这个
http://v26.huoshanvod.com/688ef4380d1527a409db928db87bbdd3/60223480/video/tos/cn/tos-cn-ve-51/098a0bcec18e436ab8836537947d5523/?a=1112&br=3708&bt=927&cd=0%7C0%7C0&ch=0&cr=0&cs=0&cv=1&dr=3&ds=3&er=&l=202102071506400102120810760E006E79&lr=&mime_type=video_mp4&pl=0&qs=0&rc=M207czlpeTxlMzMzMzYzM0ApNmVoPDM7ZGU1N2U7OzZnNmdlMmxjXmYzLTJgLS02MC9zczZhMC0tMjQzXzNgNjJgYC06Yw%3D%3D&vl=&vr=.mp4
