### ISSUE TITLE
MojitoWrapper headerSize大于0时，views没有排除header views

### ISSUE THREAD

**Issue by start141** [MikaelZero/mojito#63]
如题。导致关闭图片浏览时，会返回到错误的列表位置。

我这边用Kotlin扩展函数临时规避了这个问题（红框部分为新增内容）

<img width="512" alt="WX20210220-135549@2x" src="https://user-images.githubusercontent.com/6055764/108585423-78d3f980-7383-11eb-8e9e-1769b7c63167.png">
<img width="510" alt="WX20210220-135622@2x" src="https://user-images.githubusercontent.com/6055764/108585425-7a9dbd00-7383-11eb-9c61-46b9fd0d06a6.png">

作者可否抽空修复一下这个问题？感谢！

**Comment by MikaelZero** [comment]
demo里也有带着header和footer的，没有问题
你的header是如何添加的？

**Comment by start141** [comment]
> demo里也有带着header和footer的，没有问题
> 你的header是如何添加的？

我这里的header就是一个itemView
![image](https://user-images.githubusercontent.com/6055764/108586715-2bf42100-738b-11eb-9455-28a4025e404e.png)

**Comment by MikaelZero** [comment]
你这个是用的哪种方式addHeader的？用的哪个库，提供下代码

**Comment by start141** [comment]
另外，图片保存代码是要自行实现吗？粗略的看了一下代码，没有发现有保存的方法。

**Comment by MikaelZero** [comment]
是的，保存和这个库没有什么关联性，所以交给开发者

可以给你个参考
```
GlobalScope.launch {
                    val file: File = Glide.with(context)
                        .load(url)
                        .downloadOnly(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)
                        .get()
                    FileUtil.copyFile(file, File(FilePathConfig.IMAGE_PATH + File.separator + System.currentTimeMillis() + ".jpg"))
                }
```

**Comment by start141** [comment]
> 你这个是用的哪种方式addHeader的？用的哪个库，提供下代码

普通的adapter，只不过第一个是添加图片，所以我当成headerSize是1，实际上不叫header吧。
如果不按我上面的方式处理，那么点击第一张图片（即第2个item），返回时动画会回到第一个item。

**Comment by start141** [comment]
> 是的，保存和这个库没有什么关联性，所以交给开发者
> 
> 可以给你个参考
> 
> ```
> GlobalScope.launch {
>                     val file: File = Glide.with(context)
>                         .load(url)
>                         .downloadOnly(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)
>                         .get()
>                     FileUtil.copyFile(file, File(FilePathConfig.IMAGE_PATH + File.separator + System.currentTimeMillis() + ".jpg"))
>                 }
> ```

好的，谢谢！

**Comment by MikaelZero** [comment]
那我是否可以理解，你的第一个其实是一个item，而不是一个header

**Comment by MikaelZero** [comment]
可以提供下代码吗，我这边测试下

**Comment by start141** [comment]
> 那我是否可以理解，你的第一个其实是一个item，而不是一个header

是的。需要的效果是跟header一样的。
你看下排除header views是否可以兼任以上两种模式？

**Comment by start141** [comment]
> 可以提供下代码吗，我这边测试下

代码不好提供啊，太多耦合在一起了，你可以简单的用一个RecyclerView添加一些数据，第一个当成是“添加”按钮之类的，第二个开始才是图片，对应的adapter数据第一个删除后再设置给Mojito，效果就出来了

**Comment by MikaelZero** [comment]
使用 .position 函数的第二个参数是你前面不可点击的数量
