### ISSUE TITLE
1.6.8引入了新的Bug

### ISSUE THREAD

**Issue by start141** [MikaelZero/mojito#65]
originImageViewList数量不对了，recyclerView.childCount获取的child数据与adapter data size数量不对应。
导致RecyclerView item没有全部展示的时候，部分item退出动画异常。

**Comment by MikaelZero** [comment]
什么场景下

**Comment by start141** [comment]
RecyclerView item没有全部展示的时候

**Comment by start141** [comment]
比如说有100个item，当前页面只显示了10个，有一部分没显示的时候。
因为recyclerView.childCount数量只表示已加载的childView数量，在item未全部展示（加载）的时候recyclerView.childCount数量少于adapter data size

**Comment by start141** [comment]
1.6.7版本的方式初始化originImageViewList没有问题，1.6.8的改动导致出现的新问题

**Comment by MikaelZero** [comment]
你用demo的数据源多加几组试试看，我试了一下，没有问题

**Comment by start141** [comment]
> 你用demo的数据源多加几组试试看，我试了一下，没有问题

问题是存在的。
你在测试demo过程中（包括之前版本的demo）没有发现退出动画错误的问题是因为demo的布局有问题，
activity_display.xml根布局使用了ScrollView，而RecyclerView的高度为match_parent，导致RecyclerView加载了所有的itemView（没有复用），

要复现问题只需要给RecyclerView设置一个固定的高度，数据源多加一些，让RecyclerView可以上下滚动复用布局，将RecyclerView滚动到第一个可视的item position大于0，再点击查看大图，再退出就可以发现问题了。
或者把瀑布流页面的数据源加多一点，直接看瀑布流页面，按上述操作，就可以复现了。

**Comment by MikaelZero** [comment]
1.7.0版本已解决

上个bug的问题，经过考虑该库不作处理，可以自行在url的列表中添加空的地址来解决

```
val newUrls = mutableListOf<String>()
        newUrls.add("")
        newUrls.add("")
        newUrls.addAll(SourceUtil.getNormalImages())
        adapter.setOnItemClickListener { _, view, position ->
            if (position == 0) {
                return@setOnItemClickListener
            }
            Mojito.with(context)
                .urls(newUrls)
                .position(position, headerSize = adapter.headerLayoutCount, footerSize = adapter.footerLayoutCount)
                .views(recyclerView, R.id.srcImageView)
                .setIndicator(NumIndicator())
                .start()
        }
```

**Comment by start141** [comment]
空的地址会导致浏览图片时多出来黑色的空页面哦。需求方面肯定是过不去的。那我还是用扩展函数去除RecyclerView的header views吧。

**Comment by start141** [comment]
经测试，1.7.0版本跟之前的版本一样，如果在header位置添加空地址，会导致多出来header size数量的黑色空白页面。
需求上面肯定过不过。
我还是先用扩展函数过滤header views来解决这个问题吧。

**Comment by MikaelZero** [comment]
好像是有这个问题，不过这个场景其实不应该让这个库处理，后面再考虑考虑要不要做吧，暂时先这么处理好了

**Comment by start141** [comment]
> 好像是有这个问题，不过这个场景其实不应该让这个库处理，后面再考虑考虑要不要做吧，暂时先这么处理好了

确实是可以不用库来处理。但是因为MojitoWrapper.position方法提供了headerSize和footerSize参数，但是实际上用起来却不符合一般需求（添加了header、footer数据会多出空白页面，没有添加header、footer数据又会导致返回动画退到错误的item上面），
所以有点尴尬。

**Comment by MikaelZero** [comment]
你那个不是header，header是没有问题的，你这个情况是属于一个item

现在如果是header  需要指定数量  .position(position, headerSize = adapter.headerLayoutCount, footerSize = adapter.footerLayoutCount)

**Comment by start141** [comment]
那我觉得这种情况下的header、footer参数意义就不大了，这种简单处理完全可以让开发者自行处理position解决，这种情况下的header通常header的数据也是跟adapter data分离的，感觉没有必要封装到positon()方法参数里面。

实际上RecyclerView通常所指的header/footer就是一个类型的item吧（个人见解），对于这种情况的header，由于排除header、footer的逻辑相对比较复杂，而且MojitoWrapper也已经封装了针对RecyclerView 的views()方法，此时反而显得headerSize参数比较有意义（footerSize可以通过不添加footer数据解决，可以不提供参数）。

以上为个人意见，作者可以酌情考虑一下，谢谢啦。库本身的体验还是很好的，进出转场动画都比较完善了。

**Comment by MikaelZero** [comment]
header场景多，而且不做处理会导致动画有问题，也是昨天才测出来的问题
