### ISSUE TITLE
依赖不上

### ISSUE THREAD

**Issue by zhou7126** [mikaelzero/mojito#69]
试了很多次都依赖不了,是哪里配错了吗? 代理 手机热点和vpn都试了不行.
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve net.mikaelzero.mojito:FrescoImageLoader:1.7.0.

![image](https://user-images.githubusercontent.com/41935398/116981353-f6a86f80-acf9-11eb-9582-81cdc651a977.png)
![image](https://user-images.githubusercontent.com/41935398/116981432-0cb63000-acfa-11eb-879b-b138920f1a83.png)
![image](https://user-images.githubusercontent.com/41935398/116981441-1049b700-acfa-11eb-9632-1e777c741c03.png)

**Comment by MikaelZero** [comment]
下载demo是否能依赖上
这个依赖后面要换成maven，暂时还没换

**Comment by chenjx888** [comment]
还是依赖不了

**Comment by mikaelzero** [comment]
新版已迁移到jitpack
