### ISSUE TITLE
UI优化

### ISSUE THREAD

**Issue by sivanhe** [mikaelzero/mojito#70]
点击某一项，某一项的view用个空白view覆盖
![image](https://user-images.githubusercontent.com/30306863/117529622-16e27200-b00b-11eb-9edc-901217693715.png)

**Comment by mikaelzero** [comment]
参考 https://github.com/mikaelzero/mojito/blob/21a29a73f7cad0f4932beac3bf0fe6ebde240661/app/src/main/java/net/mikaelzero/app/PreviewActivity.kt#L67
