### ISSUE TITLE
依赖导入不进来

### ISSUE THREAD

**Issue by sivanhe** [mikaelzero/mojito#71]
在java项目中导入依赖，只能导入core的，glide和ske...的两个依赖导入不进来
implementation 'net.mikaelzero.mojito:core:1.7.0'
implementation 'net.mikaelzero.mojito:SketchImageFactory:1.7.0'
implementation 'net.mikaelzero.mojito:GlideImageLoader:1.7.0'

**Comment by mikaelzero** [comment]
新版已迁移到jitpack
