### ISSUE TITLE
ImageMojitoActivity内存泄漏

### ISSUE THREAD

**Issue by sivanhe** [mikaelzero/mojito#72]
ImageMojitoActivity存在内存泄漏问题

**Comment by mikaelzero** [comment]
能给个泄漏的截图吗

**Comment by sivanhe** [comment]
![Screenshot_2021-06-16-11-34-54-383_com yudu pi](https://user-images.githubusercontent.com/30306863/122154799-5321b180-ce98-11eb-8bdb-f91c62444d48.jpg)
这个是截图，我本来是想传hprof文件，但是传不了

**Comment by sivanhe** [comment]
[xielou.zip](https://github.com/mikaelzero/mojito/files/6660121/xielou.zip)

**Comment by sivanhe** [comment]
zip是hprof文件

**Comment by mikaelzero** [comment]
发生泄漏的时候  activity是否还在显示中？

**Comment by sivanhe** [comment]
没有显示了，点击图片/拖拽图片，界面销毁后出现的

**Comment by mikaelzero** [comment]
最好用as的profile测试下泄漏  leakcanary这个工具有时候不太靠谱  一个文件不好做对比

**Comment by mikaelzero** [comment]
我用profile测试的结果是没有泄漏的

**Comment by sivanhe** [comment]
我用profiler试了下，内存确实没有持续增加。我猜测leakcanary是检测到集合类数据没有clear没有置于null，还有fragment里的listener没有置于null导致的
![Lark20210621-102639](https://user-images.githubusercontent.com/30306863/122699045-37911f00-d27b-11eb-9ec2-55f459467199.png)

**Comment by mikaelzero** [comment]
后面做下clear好了
