### ISSUE TITLE
bintray库用不了了

### ISSUE THREAD

**Issue by Jiaozhiheng** [mikaelzero/mojito#73]
maven { url 'https://dl.bintray.com/mikaelzero/maven'} 403可 不可用了

**Comment by MikaelZero** [comment]
最近忙 有时间再迁移到mavenCenter

**Comment by dogscar** [comment]
能马上迁移吗？依赖装不上，都没法开工了。
Bintray 服务已经被停用了。
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
@MikaelZero

**Comment by dogscar** [comment]
能尽快迁移吗？依赖装不上，都没法开工了。
Bintray 服务已经被停用了。
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
@MikaelZero

**Comment by MikaelZero** [comment]
最近实在没时间 不好意思

**Comment by mikaelzero** [comment]
新版已迁移到jitpack

**Comment by dogscar** [comment]
把implementation 'com.gyf.immersionbar:immersionbar:3.0.0'改为
compileOnly 'com.gyf.immersionbar:immersionbar:3.0.0'
自己编译了一份immersionbar，这样会起冲突。
@mikaelzero

**Comment by mikaelzero** [comment]
啥冲突？

**Comment by dogscar** [comment]
重复引用，一般这种第三方非官方的包最好使用compileOnly

**Comment by mikaelzero** [comment]
可以使用exclude group解决
