### ISSUE TITLE
集成mojito后 页面切换的动画效果失效了

### ISSUE THREAD

**Issue by dirkshowtime** [mikaelzero/mojito#76]
mojito效果很棒，只是我在BaseActivity中封装的页面切换的动画效果，不知道为啥集成mojito后失效了。变成原生效果了。在gradle中注释掉依赖就恢复了，有点懵。。。。。有没有有同样问题的同学。。。
  @Override
  public void startActivity(Intent intent) {
    startActivity(intent, true);
  }

  public void startActivity(Intent intent, boolean anim) {
    super.startActivity(intent);
    if (anim) overridePendingTransition(R.anim.in_from_right, R.anim.out_to_left);
  }

  @Override
  public void startActivityForResult(Intent intent, int requestCode) {
    startActivityForResult(intent, requestCode, true);
  }

  public void startActivityForResult(Intent intent, int requestCode, boolean anim) {
    super.startActivityForResult(intent, requestCode);
    if (anim) overridePendingTransition(R.anim.in_from_right, R.anim.out_to_left);
  }

  @Override
  public void finish() {
    finish(true);
  }

  public void finish(boolean anim) {
    super.finish();
    if (anim) overridePendingTransition(R.anim.in_from_left, R.anim.out_to_right);
  }

**Comment by mikaelzero** [comment]
base中如何封装的？

**Comment by dirkshowtime** [comment]
> base中如何封装的？

好了解决了。谢谢作者老大。
是这样的
您的style 设置了windowIsTranslucent，我也不知道为啥会影响到我的项目
我参照一篇文章改好了，https://www.jianshu.com/p/31e053564857
