### ISSUE TITLE
ImageMojitoActivity onCreate 空指针异常

### ISSUE THREAD

**Issue by Louiswang86** [mikaelzero/mojito#80]
![image](https://user-images.githubusercontent.com/19605506/128329206-8e5f5e8e-4f6c-4f0e-9a62-d73d14a91b04.png)
demo也有这个问题
![image](https://user-images.githubusercontent.com/19605506/128329352-93f1c5db-8402-4c7c-a36a-ca444847c29f.png)

**Comment by Louiswang86** [comment]
Android 11 ；手机型号：MI CC9 Pro

**Comment by mikaelzero** [comment]
这个新加的没有测试过。。。 周末测试一下

**Comment by liuki2014** [comment]
https://stackoverflow.com/questions/65650589/attempt-to-invoke-virtual-method-internal-policy-decorview-getwindowinsetscontr
