### ISSUE TITLE
recycleview中打开的时候，左右滑动图片，会出现黑屏，不显示图片的情况

### ISSUE THREAD

**Issue by hyl87** [mikaelzero/mojito#81]
recycleview 中嵌套的recycleview 显示图片列表，查看大图的时候会出现

加载的都是本地图片 content://media/external/images/media/475

binding.imageCollectionView.mojito(R.id.imgCoverBg) {
            urls(list)
            position(position)
            progressLoader { DefaultPercentProgress() }
            setIndicator(NumIndicator())
 }

**Comment by mikaelzero** [comment]
是偶尔出现还是必现
是一直黑屏还是一会就好
黑屏的时候有进度条吗

**Comment by hyl87** [comment]
没有进度条。一直黑着。如果图片多。来回滑。就会出现。

**Comment by mikaelzero** [comment]
能提供下你的本地图片大概都多大吗

**Comment by hyl87** [comment]
4344X5792 最大的图片

图片太大了 上传不了超过10M了

**Comment by mikaelzero** [comment]
OK  我这边自己试下

**Comment by hyl87** [comment]
我大概知道是什么问题了，我把这个类改成glide加载了， 就没有黑屏的问题了
大概率是Sketch的缓存导致的?
![image](https://user-images.githubusercontent.com/1303038/129311747-7bda0015-aac7-4c30-b9d3-361363824703.png)

**Comment by mikaelzero** [comment]
这个模块不应该出现glide的代码的
