### ISSUE TITLE
查看大图时模糊

### ISSUE THREAD

**Issue by gydhy8** [mikaelzero/mojito#83]
作者您好，我们项目最近集成了您的查看大图依赖库，有用户反馈查看大图时模糊，手动缩放后变清晰，不知是什么原因，望指导，有没有交流群啥的？这样会快点，个人微信号：codercool

**Comment by mikaelzero** [comment]
这个和sketch的库是有关联的，他在处理超大图的时候会这样处理，我这边没有处理，如果你要修改的话，可以参考下这个
https://github.com/panpf/sketch/issues/147
当然这部分我没有测试过

**Comment by gydhy8** [comment]
好的，十分感谢

**Comment by gydhy8** [comment]
好的，十分感谢，我试试

**Comment by gydhy8** [comment]
kekegdsz 这个用户说注释掉某部分代码，但是看不了，我这边只显示一个加载失败的默认图

**Comment by gydhy8** [comment]
看到了，看来要依赖源码库并修改代码了

**Comment by gydhy8** [comment]
问题已解决

**Comment by mikaelzero** [comment]
可以贴下解决的代码
