### ISSUE TITLE
NumIndicator 和底部导航栏重叠了

### ISSUE THREAD

**Issue by lhx546920268** [mikaelzero/mojito#85]
```
     Mojito.with(context)
            .setIndicator(NumIndicator())
            .urls(urls)
            .position(position)
            .start()
```
![181629340650_ pic](https://user-images.githubusercontent.com/5548154/129998915-f578d808-1808-4a0d-bad2-3afcc16fc940.jpg)

**Comment by mikaelzero** [comment]
可以配置 transparentNavigationBar 属性为false
初始化的IMojitoConfig中
