### ISSUE TITLE
缩回时底部出现小黑条

### ISSUE THREAD

**Issue by gydhy8** [mikaelzero/mojito#86]
查看大图后点击缩回时，底部出现小黑条，窄的宽图尤其明显，高的的图片倒不明显

**Comment by mikaelzero** [comment]
能否截个图  是否有底部导航栏

**Comment by gydhy8** [comment]
https://user-images.githubusercontent.com/6811699/130218626-b16e0cf6-62f1-4839-8aff-759b56f8690d.mp4

Uploading SVID_20210820_180550_1.mp4…



这是录屏，缩回去的时候下方有个小黑条

**Comment by gydhy8** [comment]
![20210820181630](https://user-images.githubusercontent.com/6811699/130218947-55aef7aa-529c-4eec-a2a7-eb22ad7edc6a.jpg)
这是一帧截图

**Comment by mikaelzero** [comment]
我试了下没这个东西  这个看起来有点像是手机自带的？

**Comment by gydhy8** [comment]
宽的图片容易出现，方形图，高图看不到

**Comment by emptyily** [comment]
我也遇到了这个问题，有解决方案么?

**Comment by emptyily** [comment]
@gydhy8  兄弟，我找到滚动条是咋来的了,不知道你解决没
ImageZoomer中有一个ScrollBarHelper就是它搞出来的~
