### ISSUE TITLE
setActivityCoverLoader 会空指针

### ISSUE THREAD

**Issue by zanezha0** [mikaelzero/mojito#91]
setActivityCoverLoader 会空指针

**Comment by zanezha0** [comment]
Caused by: java.lang.NullPointerException: null cannot be cast to non-null type net.mikaelzero.mojito.interfaces.IMojitoFragment
2at net.mikaelzero.mojito.ui.ImageMojitoActivity.getCurrentFragment(ImageMojitoActivity.kt:184)
3at net.mikaelzero.mojito.ui.ImageMojitoActivity.onCreate(ImageMojitoActivity.kt:125)

**Comment by Youngkingtom** [comment]
+1 解决了没有
